services:
  - type: web
    name: newgate-backend
    rootDir: backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: newgate-db
          property: connectionString

databases:
  - name: newgate-db
    plan: free
    databaseName: newgate
    user: newgate
